services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.dockerfile
    container_name: youtube_subtitle-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: youtube_subtitle-backend
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: youtube_subtitle-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: youtube_subtitle-redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: youtube_subtitle-celery
    depends_on:
      - redis
      - backend
    working_dir: /backend
    env_file:
      - .env
    command: celery -A worker worker --loglevel=info --concurrency=4 --prefetch-multiplier=1

  summary_server:
    build:
      context: . # 여기를 수정
      dockerfile: ./docker/summary_server.dockerfile # 상대 경로 수정
    container_name: youtube_summary_server
    ports:
      - "8001:8000"

volumes:
  postgres_data:
  redis_data:
