services:
  web:
    build: .
    container_name: youtube_subtitle-web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:alpine
    container_name: youtube_subtitle-redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: youtube_subtitle-celery
    depends_on:
      - redis
      - web
    working_dir: /app
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A worker worker --loglevel=info --concurrency=4 --prefetch-multiplier=1
