version: "3"

services:
  web:
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
      - ./data:/data
      - ./requirements.txt:/app/requirements.txt

  worker:
    volumes:
      - ./app:/app
      - ./data:/data
      - ./requirements.txt:/app/requirements.txt
      - ~/.cache/huggingface:/root/.cache/huggingface
