services:
  web:
    build: .
    container_name: youtube_subtitle-web
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: youtube_subtitle-redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: youtube_subtitle-celery
    depends_on:
      - redis
      - web
    working_dir: /app
    env_file:
      - .env
    command: celery -A worker worker --loglevel=info --concurrency=4 --prefetch-multiplier=1
