services:
  web:
    build: .
    container_name: youtube_subtitle-web
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: youtube_subtitle-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: youtube_subtitle-redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: youtube_subtitle-celery
    depends_on:
      - redis
      - web
    working_dir: /backend
    env_file:
      - .env
    command: celery -A worker worker --loglevel=info --concurrency=4 --prefetch-multiplier=1

volumes:
  postgres_data:
  redis_data:
