services:
  backend:
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/backend
      - ./data:/data

  worker:
    volumes:
      - ./backend:/backend
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
